# Generated by Django 6.0.6 on 2026-06-07 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('user_type', models.CharField(choices=[('patient', 'Paciente'), ('doctor', 'Médico'), ('admin', 'Administrador')], default='patient', max_length=10, verbose_name='Tipo de usuário')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto de perfil')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(max_length=20, unique=True, verbose_name='CRM')),
                ('crm_state', models.CharField(max_length=2, verbose_name='Estado do CRM')),
                ('specialty', models.CharField(choices=[('obstetrics', 'Obstetrícia'), ('gynecology', 'Ginecologia'), ('maternal_fetal', 'Medicina Materno-Fetal'), ('general', 'Clínica Geral'), ('other', 'Outra')], default='obstetrics', max_length=30, verbose_name='Especialidade')),
                ('is_crm_validated', models.BooleanField(default=False, verbose_name='CRM validado')),
                ('validation_date', models.DateTimeField(blank=True, null=True, verbose_name='Data da validação')),
                ('validation_notes', models.TextField(blank=True, verbose_name='Observações da validação')),
                ('institution', models.CharField(blank=True, max_length=255, verbose_name='Instituição')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia profissional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Médico',
                'verbose_name_plural': 'Perfis dos Médicos',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestational_age_weeks', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Semana gestacional atual')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Data prevista do parto')),
                ('last_menstrual_period', models.DateField(blank=True, null=True, verbose_name='DUM (Data da última menstruação)')),
                ('blood_type', models.CharField(blank=True, max_length=5, verbose_name='Tipo sanguíneo')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Altura (cm)')),
                ('pre_gestational_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso pré-gestacional (kg)')),
                ('risk_conditions', models.TextField(blank=True, verbose_name='Condições de risco pré-existentes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='accounts.doctorprofile', verbose_name='Médico responsável')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil da Paciente',
                'verbose_name_plural': 'Perfis das Pacientes',
            },
        ),
    ]
