# Generated by Django 6.0.7 on 2026-07-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='family_medical_history',
            field=models.TextField(blank=True, verbose_name='Histórico de doenças na família'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medical_history',
            field=models.TextField(blank=True, verbose_name='Histórico médico (doenças anteriores)'),
        ),
    ]
