# Generated by Django 6.0.7 on 2026-07-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_patientprofile_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
