version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bemgestar_postgres
    restart: always
    environment:
      POSTGRES_DB: bemgestar_db
      POSTGRES_USER: bemgestar_user
      POSTGRES_PASSWORD: bemgestar_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
