# Generated by Django 6.0.7 on 2026-07-17 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField(unique=True, verbose_name='Semana Gestacional')),
                ('baby_model', models.FileField(upload_to='ar_models/', verbose_name='Modelo 3D (GLB)')),
                ('baby_model_usdz', models.FileField(blank=True, null=True, upload_to='ar_models/', verbose_name='Modelo 3D (USDZ)')),
                ('estimated_height_cm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Comprimento Estimado (cm)')),
                ('estimated_weight_grams', models.PositiveIntegerField(verbose_name='Peso Estimado (g)')),
                ('animation', models.CharField(default='sleep_idle', max_length=100, verbose_name='Animação Padrão')),
                ('scale', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Escala do Modelo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo do Bebê em RA',
                'verbose_name_plural': 'Modelos do Bebê em RA',
                'ordering': ['week'],
            },
        ),
        migrations.CreateModel(
            name='ARTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in_experience_seconds', models.PositiveIntegerField(default=0, verbose_name='Tempo na Experiência (s)')),
                ('views_count', models.PositiveIntegerField(default=1, verbose_name='Visualizações')),
                ('captures_count', models.PositiveIntegerField(default=0, verbose_name='Capturas de Foto')),
                ('model_used', models.CharField(max_length=255, verbose_name='Modelo Utilizado')),
                ('gestational_week', models.PositiveSmallIntegerField(verbose_name='Semana Gestacional')),
                ('avg_fps', models.DecimalField(decimal_places=2, default=60.0, max_digits=5, verbose_name='FPS Médio')),
                ('errors_logged', models.TextField(blank=True, verbose_name='Erros/Logs de Dispositivo')),
                ('crashes_count', models.PositiveSmallIntegerField(default=0, verbose_name='Quedas de Execução')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_telemetries', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Telemetria de RA',
                'verbose_name_plural': 'Telemetrias de RA',
                'ordering': ['-created_at'],
            },
        ),
    ]
