# Generated by Django 6.0.7 on 2026-07-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='armodel',
            name='bounding_box_x',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='Bounding Box X'),
        ),
        migrations.AddField(
            model_name='armodel',
            name='bounding_box_y',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='Bounding Box Y'),
        ),
        migrations.AddField(
            model_name='armodel',
            name='bounding_box_z',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='Bounding Box Z'),
        ),
        migrations.AddField(
            model_name='armodel',
            name='real_depth_meters',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='Profundidade Real (m)'),
        ),
        migrations.AddField(
            model_name='armodel',
            name='real_length_meters',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='Comprimento Real (m)'),
        ),
        migrations.AddField(
            model_name='armodel',
            name='real_width_meters',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='Largura Real (m)'),
        ),
    ]
