# Generated by Django 6.0.6 on 2026-06-07 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField(verbose_name='Data e hora agendada')),
                ('consultation_type', models.CharField(choices=[('in_person', 'Presencial'), ('teleconsultation', 'Teleconsulta')], default='in_person', max_length=20, verbose_name='Tipo de consulta')),
                ('location', models.CharField(blank=True, max_length=500, verbose_name='Local/Link da consulta')),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('completed', 'Realizada'), ('cancelled', 'Cancelada'), ('no_show', 'Paciente não compareceu')], default='scheduled', max_length=15, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Anotações')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Motivo do cancelamento')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Cancelado por')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations_as_doctor', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations_as_patient', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200, verbose_name='Nome do exame')),
                ('clinical_indication', models.TextField(verbose_name='Indicação clínica')),
                ('priority', models.CharField(choices=[('routine', 'Rotina'), ('urgent', 'Urgente')], default='routine', max_length=10, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Realizado'), ('cancelled', 'Cancelado')], default='pending', max_length=15, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('result_notes', models.TextField(blank=True, verbose_name='Resultado (anotações)')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Solicitado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_requests', to='consultations.consultation', verbose_name='Consulta relacionada')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_requests_issued', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='exam_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Solicitação de Exame',
                'verbose_name_plural': 'Solicitações de Exames',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_type', models.CharField(choices=[('medication', 'Medicação'), ('exam', 'Exame'), ('referral', 'Encaminhamento')], default='medication', max_length=15, verbose_name='Tipo')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('content', models.TextField(verbose_name='Conteúdo da receita')),
                ('instructions', models.TextField(blank=True, verbose_name='Instruções de uso')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válida até')),
                ('digital_signature', models.CharField(blank=True, max_length=500, verbose_name='Assinatura digital')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Emitida em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='consultations.consultation', verbose_name='Consulta relacionada')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_issued', to=settings.AUTH_USER_MODEL, verbose_name='Médico')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_received', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Receita Digital',
                'verbose_name_plural': 'Receitas Digitais',
                'ordering': ['-issued_at'],
            },
        ),
    ]
