# Generated by Django 6.0.6 on 2026-06-07 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Score (0-100)')),
                ('risk_level', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Médio'), ('high', 'Alto'), ('critical', 'Crítico')], default='low', max_length=10, verbose_name='Nível de risco')),
                ('contributing_factors', models.JSONField(default=dict, verbose_name='Fatores contribuintes')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Calculado em')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='risk_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Score de Risco',
                'verbose_name_plural': 'Scores de Risco',
                'ordering': ['-calculated_at'],
                'get_latest_by': 'calculated_at',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_type', models.CharField(choices=[('headache', 'Dor de cabeça'), ('nausea', 'Náusea'), ('vomiting', 'Vômito'), ('abdominal_pain', 'Dor abdominal'), ('bleeding', 'Sangramento'), ('swelling', 'Inchaço (edema)'), ('blurred_vision', 'Visão turva'), ('chest_pain', 'Dor no peito'), ('shortness_of_breath', 'Falta de ar'), ('reduced_fetal_movement', 'Redução dos movimentos fetais'), ('burning_urination', 'Ardência ao urinar'), ('fever', 'Febre'), ('dizziness', 'Tontura'), ('lower_back_pain', 'Dor lombar'), ('contractions', 'Contrações'), ('other', 'Outro')], max_length=30, verbose_name='Tipo de sintoma')),
                ('severity', models.CharField(choices=[('mild', 'Leve'), ('moderate', 'Moderado'), ('severe', 'Grave')], default='mild', max_length=10, verbose_name='Intensidade')),
                ('description', models.TextField(blank=True, verbose_name='Descrição livre')),
                ('duration_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Duração aproximada (horas)')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registrado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=True, verbose_name='Sincronizado')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sintoma',
                'verbose_name_plural': 'Sintomas',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pressão sistólica (mmHg)')),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Pressão diastólica (mmHg)')),
                ('heart_rate', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Frequência cardíaca (bpm)')),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('oxygen_saturation', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Saturação de oxigênio (%)')),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Glicemia (mg/dL)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Registrado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced', models.BooleanField(default=True, verbose_name='Sincronizado')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinal Vital',
                'verbose_name_plural': 'Sinais Vitais',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('hypertension', 'Hipertensão'), ('hypotension', 'Hipotensão'), ('tachycardia', 'Taquicardia'), ('fever', 'Febre'), ('low_oxygen', 'Saturação baixa'), ('high_glucose', 'Glicemia elevada'), ('severe_symptom', 'Sintoma grave'), ('high_risk_score', 'Score de risco elevado'), ('reduced_fetal_movement', 'Redução movimentos fetais'), ('general', 'Geral')], max_length=30, verbose_name='Tipo de alerta')),
                ('severity', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Atenção'), ('urgent', 'Urgente')], default='warning', max_length=10, verbose_name='Severidade')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('read_by_patient', models.BooleanField(default=False)),
                ('read_by_doctor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('risk_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.riskscore', verbose_name='Score relacionado')),
                ('symptom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.symptom', verbose_name='Sintoma relacionado')),
                ('vital_sign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.vitalsign', verbose_name='Sinal vital relacionado')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-created_at'],
            },
        ),
    ]
