# Generated by Django 6.0.7 on 2026-07-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsign',
            name='sleep_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Horas de sono'),
        ),
    ]
