# Generated by Django 6.0.7 on 2026-07-29 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_vitalsign_sleep_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('hypertension', 'Hipertensão'), ('hypotension', 'Hipotensão'), ('tachycardia', 'Taquicardia'), ('fever', 'Febre'), ('low_oxygen', 'Saturação baixa'), ('high_glucose', 'Glicemia elevada'), ('severe_symptom', 'Sintoma grave'), ('high_risk_score', 'Score de risco elevado'), ('reduced_fetal_movement', 'Redução movimentos fetais'), ('general', 'Geral')], max_length=30, verbose_name='Tipo')),
                ('severity', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Atenção'), ('urgent', 'Urgente')], default='warning', max_length=10, verbose_name='Severidade')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('read', models.BooleanField(default=False, verbose_name='Lida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Paciente relacionada')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário')),
                ('risk_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='monitoring.riskscore', verbose_name='Score relacionado')),
                ('symptom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='monitoring.symptom', verbose_name='Sintoma relacionado')),
                ('vital_sign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='monitoring.vitalsign', verbose_name='Sinal vital relacionado')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
