# Generated by Django 6.0.7 on 2026-07-30 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_notification_delete_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=120, verbose_name='Condição identificada')),
                ('severity', models.CharField(choices=[('low', 'Informativo'), ('medium', 'Atenção'), ('high', 'Urgente')], default='medium', max_length=10, verbose_name='Severidade')),
                ('reason', models.TextField(verbose_name='Motivo do alerta')),
                ('guidance', models.TextField(verbose_name='Orientações')),
                ('symptoms_used', models.JSONField(default=list, verbose_name='Sintomas utilizados')),
                ('vital_signs_used', models.JSONField(default=dict, verbose_name='Sinais vitais utilizados')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('resolved', 'Resolvido')], default='active', max_length=10, verbose_name='Status')),
                ('viewed', models.BooleanField(default=False, verbose_name='Visualizado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('related_symptom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_alerts', to='monitoring.symptom', verbose_name='Sintoma relacionado')),
                ('related_vital_sign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_alerts', to='monitoring.vitalsign', verbose_name='Sinal vital relacionado')),
            ],
            options={
                'verbose_name': 'Alerta Clínico',
                'verbose_name_plural': 'Alertas Clínicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='clinical_alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='monitoring.clinicalalert', verbose_name='Alerta clínico relacionado'),
        ),
    ]
