# Generated by Django 6.0.7 on 2026-07-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_clinicalalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('clinical_alert', 'Alerta Clínico'), ('appointment_scheduled', 'Consulta Agendada'), ('appointment_updated', 'Consulta Alterada'), ('appointment_cancelled', 'Consulta Cancelada'), ('appointment_reminder', 'Lembrete de Consulta'), ('exam_requested', 'Solicitação de Exame'), ('exam_result', 'Resultado de Exame'), ('chat_message', 'Mensagem do Chat'), ('hypertension', 'Hipertensão'), ('hypotension', 'Hipotensão'), ('tachycardia', 'Taquicardia'), ('fever', 'Febre'), ('low_oxygen', 'Saturação baixa'), ('high_glucose', 'Glicemia elevada'), ('severe_symptom', 'Sintoma grave'), ('high_risk_score', 'Score de risco elevado'), ('reduced_fetal_movement', 'Redução movimentos fetais'), ('general', 'Geral')], max_length=50, verbose_name='Tipo'),
        ),
    ]
