# Generated by Django 6.0.6 on 2026-06-07 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Categoria')),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ícone')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('summary', models.TextField(verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo completo')),
                ('content_type', models.CharField(choices=[('article', 'Artigo'), ('video', 'Vídeo'), ('infographic', 'Infográfico'), ('guide', 'Guia')], default='article', max_length=15, verbose_name='Tipo')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='education/thumbnails/', verbose_name='Thumbnail')),
                ('external_url', models.URLField(blank=True, verbose_name='URL externa (vídeo etc.)')),
                ('week_start', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Semana gestacional inicial (inclusive)')),
                ('week_end', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Semana gestacional final (inclusive)')),
                ('target_risk_level', models.CharField(choices=[('all', 'Todos os perfis'), ('low', 'Baixo risco'), ('medium', 'Médio risco'), ('high', 'Alto risco'), ('critical', 'Crítico')], default='all', max_length=10, verbose_name='Perfil de risco alvo')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tags (separadas por vírgula)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='education.contentcategory', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Conteúdo Educativo',
                'verbose_name_plural': 'Conteúdos Educativos',
                'ordering': ['week_start', '-created_at'],
            },
        ),
    ]
